# init app
init_app:
	# python3.10 main.py init-app quant/board
	python3.10 main.py init-app quant/signal

gen_model:
	# python3.10 main.py g --class-name QuantBoard --zh-name 版块 --en-name board
	python3.10 main.py g --class-name QuantBoard --zh-name 版块 --en-name board

init_db:
	python3.10 main.py init
run:
	python3.10 main.py run

migrate:
	python3.10 main.py migrate

